SELECT TABLE_SCHEMA, TABLE_NAME FROM
INFORMATION_SCHEMA.TABLES TABLES 
	WHERE
TABLE_SCHEMA NOT IN
('information_schema','pg_catalog')
AND
table_type='BASE TABLE'
ORDER BY TABLE_SCHEMA,TABLE_NAME


CREATE TABLE IF NOT EXISTS SETORES(
    NUM_DEPTO UUID DEFAULT gen_random_uuid() NOT NULL,
    NOME_DEPTO VARCHAR(60) NOT NULL,
    CONSTRAINT SETORES_PK PRIMARY KEY(NUM_DEPTO)
);

INSERT INTO SETORES (NOME_DEPTO) VALUES
('VENDAS'),
('DEVS')

SELECT * FROM SETORES

--DROP TABLE SETORES

SELECT column_name, data_type, character_maximum_length, is_nullable
FROM information_schema.columns
WHERE table_name = 'DEPARTAMENTO'
ORDER BY ordinal_position;



--MOSTRAR TIPOS DE CAMPOS DE UMA TABELA
SELECT 
    c.table_schema,
    c.table_name,
    c.column_name,
    c.data_type,
    c.column_default LIKE 'nextval%' AS is_serial
FROM 
    information_schema.columns c
WHERE 
    c.table_name = 'DEPARTAMENTO'
ORDER BY 
    c.ordinal_position;


CREATE VIEW visao_usuario as (

--CONSULTA JOIN
SELECT 
e.MATRICULA,
e.NOME_EMPREGADO,
e.SALARIO,
d.NOME_DEPTO
FROM
EMPREGADO e
JOIN
DEPARTAMENTO d ON e.NUM_DEPTO=d.NUM_DEPTO);



select * from visao_usuario  --executar a view

select nom_empregado,nome_depto from visao_usuario -- view com colunas selecionados



CREATE VIEW visao_usuario as (

--CONSULTA JOIN
SELECT 
d.NUM_DEPTO,
d.NOME_DEPTO
FROM
EMPREGADO e
JOIN
DEPARTAMENTO d ON e.NUM_DEPTO=d.NUM_DEPTO
GROUP BY
d.NUM_DEPTO, d.NOME_DEPTO);







CREATE OR REPLACE VIEW VIEW_EMPREGADO_DEPARTAMENTO AS
SELECT 
    d.NUM_DEPTO,
    d.NOME_DEPTO,
    COUNT(e.MATRICULA) AS QUANTIDADE_EMPREGADOS,
    ROUND(SUM(e.SALARIO), 2) AS SOMA_SALARIOS,
    ROUND(AVG(e.SALARIO), 2) AS MEDIA_SALARIAL,
    (
        SELECT 
            ROUND(SUM(SALARIO), 2)
        FROM 
            EMPREGADO
    ) AS SOMA_TOTAL_SALARIOS,
    (
        SELECT 
            COUNT(MATRICULA)
        FROM 
            EMPREGADO
    ) AS TOTAL_EMPREGADOS
FROM 
    DEPARTAMENTO d
LEFT JOIN 
    EMPREGADO e ON d.NUM_DEPTO = e.NUM_DEPTO
GROUP BY 
    d.NUM_DEPTO, d.NOME_DEPTO;

select * from VIEW_EMPREGADO_DEPARTAMENTO








CREATE OR REPLACE VIEW VIEW_EMPREGADO_DEPARTAMENTO AS
SELECT 
    d.NUM_DEPTO,
    d.NOME_DEPTO,
    COUNT(e.MATRICULA) AS QUANTIDADE_EMPREGADOS,
    ROUND(SUM(e.SALARIO), 2) AS SOMA_SALARIOS,
    ROUND(AVG(e.SALARIO), 2) AS MEDIA_SALARIAL,
    t.SOMA_TOTAL_SALARIOS,
    t.TOTAL_EMPREGADOS
FROM 
    DEPARTAMENTO d
LEFT JOIN 
    EMPREGADO e ON d.NUM_DEPTO = e.NUM_DEPTO
CROSS JOIN (
    SELECT 
        ROUND(SUM(SALARIO), 2) AS SOMA_TOTAL_SALARIOS,
        COUNT(MATRICULA) AS TOTAL_EMPREGADOS
    FROM 
        EMPREGADO
) t
GROUP BY 
    d.NUM_DEPTO, d.NOME_DEPTO, t.SOMA_TOTAL_SALARIOS, t.TOTAL_EMPREGADOS;

CREATE OR REPLACE VIEW VIEW_TOTAL_SALARIOS_FUNCIONARIOS AS
SELECT 
    ROUND(SUM(SALARIO), 2) AS TOTAL_SALARIOS,
    COUNT(MATRICULA) AS TOTAL_FUNCIONARIOS,
    ROUND(AVG(SALARIO), 2) AS MEDIA_SALARIAL
FROM 
    EMPREGADO;

select * from VIEW_TOTAL_SALARIOS_FUNCIONARIOS

