-- ESQUEMA RELACIONAL EXEMPLO
-- EMPREGADO (MATRICULA, NOME_EMPREGAGO, SALARIO, NUM_DEPTO)
-- DEPARTAMENTO (NUM_DEPTO, NOME_DEPTO)
-- PROJETO (NUM_PROJ, NOME_PROJETO, LUGAR)

CREATE TABLE IF NOT EXISTS PROJETO(
	NUM_PROJ SERIAL NOT NULL,
	NOME_PROJETO VARCHAR(100)NOT NULL ,
	LUGAR VARCHAR(40)NOT NULL,
	CONSTRAINT PROJETO_PK PRIMARY KEY(NUM_PROJ)
	);

SELECT * FROM PROJETO; -- SELECIONA TABELA PROJETO

--CRIAR TABELA DE PROJETOS CONFORME ESTUDADO.

-- TRABALHA (MAT_EMPREGADO, NUM_PROJ, HORAS)
CREATE TABLE IF NOT EXISTS TRABALHA(
	MAT_EMPREGADO INT,
	NUM_PROJETO INT,
	HORAS VARCHAR(10),
	--CHAVE PRIMARIA
	CONSTRAINT TRABALHA_EMP_PROJ_PK PRIMARY KEY
	(MAT_EMPREGADO,NUM_PROJETO),
	--CHAVE ESTRANGEIRA
	CONSTRAINT TRABALHA_EMPREGADO_FK FOREIGN KEY (MAT_EMPREGADO)
	REFERENCES EMPREGADO (MATRICULA),
	CONSTRAINT TRABALHA_PROJETO_FK FOREIGN KEY (NUM_PROJETO)
	REFERENCES PROJETO (NUM_PROJ)

);

INSERT INTO PROJETO (nome_projeto,lugar)values
	('Uberaba','Iturama');

INSERT INTO TRABALHA(MAT_EMPREGADO,NUM_PROJETO,HORAS) VALUES
	(106,1,30)

	SELECT * FROM EMPREGADO
	SELECT * FROM TRABALHA
	SELECT * FROM PROJETO

-- DEPENDENTE (MATRICULA_EMPREG, NOME_DEPENDENTE, GRAU_PARENTESCO)
-- DROP TABLE DEPARTAMENTO;
-- DROP DATABASE SANKHYA;
CREATE TABLE IF NOT EXISTS DEPENDENTE(
	MATRICULA_EMPREG INT NOT NULL, 
	NOME_DEPENDENTE VARCHAR(80) NOT NULL, 
	GRAU_PARENTESCO VARCHAR (60) NOT NULL
);

	
CREATE TABLE IF NOT EXISTS DEPARTAMENTO(
	NUM_DEPTO SERIAL NOT NULL,
	NOME_DEPTO VARCHAR(60) NOT NULL,
	--CHAVE PRIMÁRIA
	CONSTRAINT DEPARTAMENTO_PK PRIMARY KEY(NUM_DEPTO)
);

CREATE TABLE IF NOT EXISTS EMPREGADO(
	MATRICULA SERIAL NOT NULL,
	NOME_EMPREGAGO VARCHAR(50) NOT NULL,
	SALARIO DECIMAL(10,2),
	NUM_DEPTO INT,
	--CHAVE PRIMÁRIA
	CONSTRAINT EMPREGADO_PK PRIMARY KEY (MATRICULA),
	--CHAVE ESTRANGEIRA
	CONSTRAINT EMPREG_DEPTO_FK FOREIGN KEY (NUM_DEPTO)
	REFERENCES DEPARTAMENTO(NUM_DEPTO)
	--REGRAS DE NEGÓCIO
-- 	CONSTRAINT EMPREGADO_CONST_NOME UNIQUE(NOME_EMPREGADO),
-- 	CONSTRAINT EMPREGADO_CHECK CHECK (SALARIO > 2000)
);
-- SELECT * FROM EMPREGADO
-- SELECT * FROM DEPARTAMENTO

-- DDL (CREATE, DROP, ALTER)
-- ADICIONANDO COLUNAS
ALTER TABLE EMPREGADO ADD sexo char;
ALTER TABLE EMPREGADO ADD COLUMN email TEXT CHECK (email <> '');
--REMOVENDO COLUNAS
ALTER TABLE EMPREGADO DROP COLUMN EMAIL;
ALTER TABLE EMPREGADO DROP COLUMN CONTATO;
ALTER TABLE EMPREGADO DROP COLUMN SEXO;
-- ADICIONAR REGRA
ALTER TABLE EMPREGADO ALTER COLUMN SEXO SET NOT NULL;
-- ADICIONANDO COLUNA JA COM VALOR DEFAULT
ALTER TABLE EMPREGADO ALTER COLUMN email SET DEFAULT 'nome@nome.com';
-- REMOVER VALOR DEFAULT
ALTER TABLE EMPREGADO ALTER COLUMN EMAIL DROP DEFAULT;
-- MUDAR O TIPO DE DADOS DE UMA COLUNA
ALTER TABLE EMPREGADO ALTER COLUMN SALARIO TYPE REAL;
ALTER TABLE EMPREGADO ALTER COLUMN SALARIO TYPE NUMERIC(10,2);

-- SELECT * FROM EMPREGADO
-- RENOMEAR UMA COLUNA
ALTER TABLE EMPREGADO RENAME COLUMN NOME_EMPREGAGO TO NOME_EMPREGADO;

-- RENOMEAR UMA TABELA
ALTER TABLE EMPREGADO RENAME TO FUNCIONARIOS;
ALTER TABLE FUNCIONARIOS RENAME TO EMPREGADO;


-- INSERINDO DADOS EM UM BD SQL
-- CADASTRANDO DEPARTAMENTOS (SELECT * FROM DEPARTAMENTO)
INSERT INTO DEPARTAMENTO (NOME_DEPTO) VALUES 
('ALMOXARIFADO'),
('AUDITORIA INTERNA'),
('BENEFÍCIOS'),
('COBRANÇA'),
('COMERCIAL'),
('COMPLIANCE'),
('COMPRAS'),
('COMUNICAÇÃO CORPORATIVA'),
('CONTABILIDADE'),
('CONTROLADORIA'),
('CRÉDITO E RISCO'),
('CUSTOS'),
('DESENVOLVIMENTO DE PRODUTOS'),
('DESENVOLVIMENTO ORGANIZACIONAL'),
('DISTRIBUIÇÃO'),
('E-COMMERCE'),
('ENGENHARIA'),
('EXPANSÃO'),
('EXPEDIÇÃO'),
('FINANCEIRO'),
('FOLHA DE PAGAMENTO'),
('GESTÃO DE PROJETOS'),
('INOVAÇÃO'),
('INTELIGÊNCIA DE MERCADO'),
('JURÍDICO'),
('LOGÍSTICA'),
('MANUTENÇÃO'),
('OPERAÇÕES'),
('PATRIMÔNIO'),
('PESQUISA E DESENVOLVIMENTO (P&D)'),
('PLANEJAMENTO ESTRATÉGICO'),
('PRODUÇÃO'),
('QUALIDADE'),
('RECRUTAMENTO E SELEÇÃO'),
('RELACIONAMENTO COM INVESTIDORES'),
('RELAÇÕES INSTITUCIONAIS'),
('RELAÇÕES PÚBLICAS'),
('RESPONSABILIDADE SOCIAL CORPORATIVA (RSC)'),
('SEGURANÇA DA INFORMAÇÃO'),
('SEGURANÇA DO TRABALHO'),
('SERVIÇO DE ATENDIMENTO AO CLIENTE (SAC)'),
('SUPORTE TÉCNICO'),
('SUPRIMENTOS'),
('SUSTENTABILIDADE'),
('TESOURARIA'),
('TI (TECNOLOGIA DA INFORMAÇÃO)'),
('TREINAMENTO E DESENVOLVIMENTO');

-- CADASTRANDO EMPREGADOS
INSERT INTO EMPREGADO (NOME_EMPREGADO, SALARIO, NUM_DEPTO) VALUES
('SIMONE GONÇALVES',3800,52),
('TEREZINHA SOUZA',3800,52),
('DÉBORA DIAS',3800,52),
('RAIMUNDA OLIVEIRA',3800,52),
('RENATA RODRIGUES',3800,52),
('JOSEFA SILVA',3900,51),
('DÉBORA DE SOUSA',3900,51),
('VERA GOMES',3800,51),
('LARISSA LIMA',3800,51),
('AMANDA BEZERRA',3800,51),
('ANA NASCIMENTO',3900,50),
('MARIANA NASCIMENTO',3900,50),
('LETÍCIA MACHADO',3900,50),
('ANA LOPES',3900,49),
('MARIANA CARVALHO',3900,49),
('ANDRÉIA GONÇALVES',3900,49),
('JÚLIA VIEIRA',4000,48),
('FABIANA SOARES',4000,48),
('JÚLIA ARAUJO',4000,48),
('FRANCISCA ARAUJO',4100,47),
('SÔNIA BARBOSA',4100,47),
('RITA BEZERRA',4100,47),
('ANTÔNIA MACHADO',4000,47),
('CRISTIANE ALVES',4000,47),
('AMANDA COSTA',4200,46),
('SANDRA GOMES',4100,46),
('CLÁUDIA DE SOUSA',4100,46),
('TEREZINHA SANTANA',4200,45),
('ALINE ALMEIDA',4200,45),
('VERA CARVALHO',4200,45),
('CLÁUDIA BARBOSA',4200,44),
('ROSÂNGELA ARAUJO',4200,44),
('BEATRIZ BEZERRA',4200,44),
('TEREZINHA NASCIMENTO',4300,43),
('SÔNIA DO NASCIMENTO',4200,43),
('LARISSA SOUZA',4200,43),
('BRUNA ARAUJO',4300,42),
('AMANDA GONÇALVES',4300,42),
('LUANA RAMOS',4300,42),
('APARECIDA NUNES',5100,41),
('LARISSA RODRIGUES',4500,41),
('VANESSA DA SILVA',4400,41),
('ANTÔNIA MARTINS',5400,40),
('JÉSSICA MARQUES',5300,40),
('FRANCISCA LIMA',5200,40),
('ALINE COSTA',5400,39),
('VANESSA MARTINS',5400,39),
('BEATRIZ SILVA',5500,38),
('NATÁLIA SOUSA',5500,38),
('SIMONE RODRIGUES',5400,38),
('LARISSA GOMES',5600,37),
('RAIMUNDA SOUZA',5600,37),
('LETÍCIA MOREIRA',5500,37),
('SIMONE MARQUES',5700,36),
('JAQUELINE DIAS',5700,36),
('ALINE ARAUJO',5600,36),
('RAQUEL ALVES',5800,35),
('ROSA LOPES',5700,35),
('PATRÍCIA DE LIMA',5700,35),
('CLÁUDIA SILVA',5900,34),
('SÔNIA TEIXEIRA',5800,34),
('JAQUELINE TEIXEIRA',5800,34),
('FRANCISCA BEZERRA',5800,34),
('CARLA DE ARAUJO',5800,34),
('GABRIELA SILVA',6000,33),
('LARISSA DE LIMA',6000,33),
('JAQUELINE SANTANA',5900,33),
('ANTÔNIA LOPES',5900,33),
('LARISSA MENDES',6200,32),
('MÁRCIA DE OLIVEIRA',6100,32),
('ROSA DE LIMA',6100,32),
('DÉBORA MOREIRA',6300,31),
('ROSA DE SOUSA',6300,31),
('ROSA MARQUES',6200,31),
('ADRIANA CARVALHO',6400,30),
('ELIANE VIEIRA',6400,30),
('SIMONE SOUZA',6400,30),
('NATÁLIA RODRIGUES',6500,29),
('ADRIANA DE ALMEIDA',6500,29),
('DÉBORA DE OLIVEIRA',6600,28),
('APARECIDA FERREIRA',6500,28),
('CAMILA DO NASCIMENTO',6500,28),
('BEATRIZ DOS SANTOS',6900,27),
('LÚCIA DE CARVALHO',6900,27),
('ALINE DA SILVA',6800,27),
('CRISTIANE DE SOUZA',7100,26),
('DANIELA SOUZA',7100,26),
('BRUNA VIEIRA',7000,26),
('LUANA DOS SANTOS',7300,25),
('JAQUELINE MARQUES',7200,25),
('NATÁLIA ALMEIDA',7200,25),
('FABIANA TEIXEIRA',3800,11),
('ÂNGELA CARDOSO',3800,11),
('JULIANA SANTANA',3700,11),
('DÉBORA DE ALMEIDA',3700,11),
('ROSÂNGELA ARAUJO',3700,11),
('JÉSSICA ALMEIDA',3700,11),
('CARLA NUNES',3700,11),
('JAQUELINE DIAS',3700,11),
('JOSEFA ROCHA',3600,11);



--
ALTER TABLE DEPARTAMENTO ADD CONSTRAINT DEPTO_UNICO UNIQUE (NOME_DEPTO)

SELECT* FROM EMPREGADO



SELECT * FROM EMPREGADO
WHERE nome_empregado LIKE 'CA%';