---EXTRAÇÃO DE DADOS (SELECT)
-- PROJEÇÃO

--SELECT <LISTA DE ATRIBUTOS> FROM <TABELA>
--SELECT * FROM EMPREGADO
SELECT matricula,nome_empregado from empregado

-- CLÁUSULA WHERE
-- SELECT <LISTA DE ATRIBUTOS> FROM <TABELAS> WHERE <CONDIÇÃO>

-- OPERADORES RELACIONAIS
-- <> OU != DIFERENTE
-- >,<,=,>=,<=
-- OPERADORES LÓGICOS
-- AND, OR, NOT

-- LISTAR NOME, SALARIO DOS EMPREGADOS DO DEPTO 03
SELECT NUM_DEPTO, NOME_EMPREGADO, SALARIO FROM EMPREGADO
WHERE NUM_DEPTO=3 AND SALARIO >=5000
LIMIT 5

--LISTAR OS EMPREGADOS COM SALARIO ENTRE 2000 E 5000
SELECT NUM_DEPTO, NOME_EMPREGADO, SALARIO FROM EMPREGADO
WHERE SALARIO >=2000 AND SALARIO<=5000

--BETWEEN E NOT BETWEEN
	
SELECT NUM_DEPTO, NOME_EMPREGADO, SALARIO FROM EMPREGADO
WHERE SALARIO NOT BETWEEN 2000 AND 5000 ORDER BY 3 DESC

SELECT * FROM EMPREGADO
	WHERE NOME_EMPREGADO LIKE '%CARLOS%'

--CLAUSULAS ORDER BY
SELECT * FROM EMPREGADO
ORDER BY SALARIO,NOME_EMPREGADO ASC;


SELECT NOME_EMPREGADO, SALARIO AS SALARIO_ANTIGO,(SALARIO *1.4)AS NOVO_SALARIO
FROM EMPREGADO WHERE SALARIO<=5000 AND NUM_DEPTO=12
	;


---FUNÇOES DE AGREGAÇÃO
---
SELECT AVG(SALARIO) FROM EMPREGADO

SELECT NOME_EMPREGADO ,SALARIO FROM EMPREGADO WHERE
SALARIO IN (SELECT MAX(SALARIO) FROM EMPREGADO);


---QUANTOS EMPREGADOS GANHAM MAIS QUE 8000
SELECT COUNT(*) FROM EMPREGADO WHERE SALARIO>8000

---QUAIS OS DIFERENTES SALARIOS PAGOS 
SELECT DISTINCT (SALARIO) FROM EMPREGADO


